### ISSUE TITLE
ポスト時の前後の空文字や改行コードの扱いの問題

### ISSUE THREAD

**Issue by so-asano** [kawaikute-gomen/baisoni#1]
問題点:
- ポスト画面で本文テキストの前後に入力した空白文字や改行コードが残り文字数にカウントされて表示される。
- その状態でポストした場合にはデータの本文テキストに前後の空白や改行コードが残る（ただしアプリ上では表示されない？）。
- さらに、本文テキストが空白や改行のみの投稿が可能となってしまっている。

公式アプリを参考に以下の修正を提案します:
- ポスト画面では本文テキストをトリムした上で文字数をカウントし表示する。
- ポストする際には本文テキストをトリムする。
- 前後の空白をトリムした上で文字数が 0 の場合はポストを不可とする。

よろしくお願いします。

**Comment by so-asano** [comment]
- 調べて驚いたが、公式アプリでは本文テキスト前後の空行と改行はフィード上などでそのまま表示している。
- ただし、これをやることにあまり意味はなさそうにもおもえる。いちおう公式アプリとの挙動の違いということで追記しておく。

**Comment by so-asano** [comment]
- リプライのポスト画面にも同様の修正が必要だったが見落としていた。

**Comment by kawaikute-gomen** [comment]
リプライのPostModalのほうも......おっと先を越されていた
ありがとうございます！これでさらに''''''''''Nirvana'''''''''に一歩近付きました

**Comment by kawaikute-gomen** [comment]
挙げていただいた問題点については修正を確認できました。ありがとうございます。
ContentTextの先頭と末尾の空白は削除できているので良い感じなのですが、テキストの間の空白までも削除されているようでして、テキスト間の空白は削除対象とせず、またカウントに加味しても良いかと思われます。
また、postmodalに改行や空白文字のみ入っている場合は、文字カウントとcircleは非表示にしても良いかもしれませんね。

どうぞよろしくお願いします。

**Comment by kawaikute-gomen** [comment]
postのデータを確認したところ、削除はされておらず、どうやら別のtextを形成するcomponentに問題があるみたいです。
すみません。死んで詫びます。
