### ISSUE TITLE
inbox 画面でのポストの相対時刻表示が誤っている

### ISSUE THREAD

**Issue by so-asano** [kawaikute-gomen/baisoni#13]
- 直近のほとんどが now になっている。

**Comment by so-asano** [comment]
@kawaikute-gomen 

- 原因は比較用の日付オブジェクトの日付演算によるものだとおもわれる。
- 日付オブジェクトを作り直すことで対応した。
- inbox 以外でなぜ再現しなかったかは不明。

よろしくお願いします。

**Comment by kawaikute-gomen** [comment]
修正の確認ができました。
ありがとうございます！
