### ISSUE TITLE
任意の URL を指定した際にトップにリダイレクトされることがある

### ISSUE THREAD

**Issue by so-asano** [kawaikute-gomen/baisoni#15]
- 具体的には `/?feed=following` にリダイレクトされる。

**Comment by so-asano** [comment]
- 直接は関連ないけど、`useRequiredSession` が挙動不審なのであわせて直したい。

**Comment by so-asano** [comment]
@kawaikute-gomen 

先に気になっていたセッションのリストアに関連する処理を修正してみました。
ご確認よろしくお願いします。

**Comment by so-asano** [comment]
@kawaikute-gomen 

- 関連してプリファレンスとフィードジェネレータの取得に関する処理を `ViewHeader` から `AppConatiner` に移動する。

これも同じブランチで修正します。

**Comment by so-asano** [comment]
@kawaikute-gomen 

修正しました。ご確認よろしくお願いします。

**Comment by so-asano** [comment]
@kawaikute-gomen 

リダイレクトのほうの問題をとりあえず修正しました。

**Comment by kawaikute-gomen** [comment]
問題の修正と解決を確認しました。
マージが完了しましたので、クローズといたします。
