### ISSUE TITLE
リンクURL の表示が長い場合に右側にはみでてしまう

### ISSUE THREAD

**Issue by so-asano** [kawaikute-gomen/baisoni#19]
下記の箇所で確認できる:
- ポスト一覧画面の本文内リンクとリンクカードの URL 表示。
- ポスト画面の本文内リンクとリンクカードの URL 表示。

**Comment by so-asano** [comment]
@kawaikute-gomen 

とりあえず、`overflow-clip` で対応してみました。`truncate-ellipse` のほうがよかったんですが、うまくいかず。
理想は改行表示ですが、これは `Chip` は対応してないみたいですね。

**Comment by kawaikute-gomen** [comment]
問題の修正を確認しました。ありがとうございます。
ただ、<Chip>で実装すると、リンクがはみ出た際に隠れてしまって、URLの検証が意味をなさなくなることに気がつきました。
そういった観点によりoverflowしたものが隠れるのは不本意なので、リンク表示の実装に関しては、もう少し考えたいと思います。

**Comment by kawaikute-gomen** [comment]
問題の修正を確認しました。
併せてマージも完了しましたので、これにてクローズといたします。
