### ISSUE TITLE
想い出は空に…

### ISSUE THREAD

**Issue by nostr-bluesky** [kawaikute-gomen/baisoni#2]
コードがかけなくてもイシューはできると，とある音符のような人に言われたのでやってきました．

**Comment by kawaikute-gomen** [comment]
@nostr-bluesky 
高倉健さんおはよう御座います。
私は最近、朝の5時ほどまでコードを書いて寝る生活をしているおかげで、午後に起きることが多くなってきました。
自分、不器用ですから。

さて、本日はNostr-Blueskyさんに来ていただいたことですし、すだちうどんをお昼ごはんとしたいと思います。

p.s.
イシューについては、バンバン出していただけると助かります。

**Comment by so-asano** [comment]
@nostr-bluesky
すごくだいたんな ID のひとがきた。

@kawaikute-gomen 
このイシューは意味ないんで、なんか残酷なラベルをつけてクローズしたいところですね。そういえば #1 もラベルつけておかないといけないですね。お願いできます？（こっちに書くのもアレですが）
