### ISSUE TITLE
Inbox で画面更新時に一瞬だけ背景画像がみえる

### ISSUE THREAD

**Issue by so-asano** [kawaikute-gomen/baisoni#21]
再現手順:
1. ホーム画面を開く。
2. 画面下部のボタンから Inbox に遷移する。
3. Inbox 画面の読み込み完了後（？）に一瞬だけ背景画像がみえる。

**Comment by so-asano** [comment]
@kawaikute-gomen 

これってほかの修正で再現しなくなったんですかね？
いまは再現ないようですが。

**Comment by kawaikute-gomen** [comment]
@so-asano 
冗長だった処理が改善されたことによって再現しなくなった可能性はありますね。
今はこの問題ないようですし、一旦closeして、また再発したらreopenしてもいいかもしれませんね

**Comment by so-asano** [comment]
@kawaikute-gomen 

了解です。では、クローズでお願いします。
