### ISSUE TITLE
ポストの作成日時表示を改善してほしい

### ISSUE THREAD

**Issue by so-asano** [kawaikute-gomen/baisoni#5]
問題点:
- 今はポスト一覧表示画面では~~日付表示しかない。~~ 当日の時間表示か日付表示しかない。
- また、ポスト個別の画面では `createdAt` に入っている変な文字列が表示される。

提案:
- 相対時間表示での表示を可能にしたほうがよい（ごく一般的なマイクロブログでそうであるように）。
- 人間が読んでわかりやすい日時表示をしたほうがよい（公式だと "Sep 20, 2023 at 18:17" みたいなかんじ。英語表記ですが）。

まあ手が回ってないだけだとおもいますが。
公式クライアントと同じ仕様でよければぼくがやっておきますよ。

**Comment by kawaikute-gomen** [comment]
後ほど、設定画面を作る際、絶対 / 相対時間の切り替えを行えるようにしたいので、今は仮の変数か何かで設定していただいて、値の受け渡しを想定して切り替えられるようにしていただけると嬉しいです

**Comment by so-asano** [comment]
@kawaikute-gomen

とりあえず先ほどの話どおり、ポスト一覧画面のみ対応してみました。
問題点としては、秒数などが時間経過によって変化しません。
これに対応するには各フィード画面に手を入れなければいけないかなと。

> 今は仮の変数か何かで設定していただいて、値の受け渡しを想定して切り替えられるようにしていただけると嬉しいです

日時表示文字列をつくる関数に `absoluteTimeOnly` という引数をいれてポーズだけとってみました。
絶対時間の表示仕様が決まってないのであんまり意味ないですが…。

**Comment by so-asano** [comment]
@kawaikute-gomen 

修正をプッシュしました。修正内容は下記のとおり:

- 日時表示の仕様を変更。
- 相対時刻表示のためにタイマーを追加（1 分間隔）。

**Comment by so-asano** [comment]
@kawaikute-gomen 

修正をプッシュしました。修正内容は下記のとおり:
- タイマーの実装箇所を変更（パフォーマンス改善のため）。
- key が重複している問題があったので対応。

**Comment by kawaikute-gomen** [comment]
- aタグの中にaタグが含まれるエラーを修正
