### ISSUE TITLE
ポスト画面に自分のアバターが表示されない

### ISSUE THREAD

**Issue by so-asano** [kawaikute-gomen/baisoni#9]
- 現在はダミー画像がつかわれている？
- サインイン時に `getProfile` してアバターの URL を取得し、使用するように修正する。

**Comment by so-asano** [comment]
@kawaikute-gomen 

- とりあえず動くとおもいます。雑ですが。
- サインイン時のタイミングだとなぜかうまくいかなかったのでタイミングは変えました。
- デフォルトの画像（アバターがない場合）が必要だとおもいます。

**Comment by kawaikute-gomen** [comment]
- アバターがない場合、FontAwesomeIconのfaUserを一時的に初期アイコンとしました。

**Comment by kawaikute-gomen** [comment]
修正完了ですので、closeします
